KaidanIM/Kaidan

- LICENSE.GPLv3.txt
- LICENSE.txt
Is this so ok? I mean naming it LICENSE.txt and LICENSE.GPLv3.txt.
We can add e.g. 'License of media', 'License of documentation' and of course licenses of integrated libraries later to the LICENSE.txt.
> Make everything GPLv3 or later

- app/source/main.cpp
QUrl::fromLocalFile() expects local file to exist thus it doesn't work with regular builds.
> Use resources to load QML files

- README.md
- src/qml/LoginPage.qml
When the debian package for Kirigami 2.0 is out, we can
also update Kirigami.
> Update QtQuick Controls

- CMakeLists.txt
- README.md
It's minimally faster and you'll get a cleaner output if you disable i18n support. At the moment I don't know how to suppress the output of the qt linguist tools. I'd like to make it optional (and disabled per default). In the README, I added the option for turning it on.
> CMake: Make i18n support optional

- src/Kaidan.cpp
I want to change this, because the default is so, too. #56 also saves the new db in `~/.local/share/KaidanIM/kaidan/...`.
> Rename settings file (kaidan/kaidan -> KaidanIM/kaidan)

- src/qml/ChatPage.qml
This just fixes the rectangles in the background of a chat's messenges, and adds a few new design features like minimal rounded corners. If you don't like those, I will remove them from the pr to make the chat usable soon.
Closes #13
> Improve chat design

- src/Kaidan.cpp
- src/Kaidan.h
The new JID resource is accesiable via `kaidan.jidResource` from QML.
It is loaded/saved into "auth/resource" into the settings.
> Add custom JID resources, Clean up Kaidan.cpp/h

- src/RosterController.cpp
- src/RosterController.h
This introduces the new QML-side functions:
`kaidan.rosterController.addContact(jid, name)`
`kaidan.rosterController.removeContact(jid)`
Currently they are not used.
In my tests there was just one problem: The roster (UI) doesn't refreshes when a contact was removed, but whenever a contact was added. (Idk why)
> Add roster add/remove contact functions

- kaidan_qml.qrc
- src/qml/AddContactPage.qml
- src/qml/GlobalDrawer.qml
- src/qml/RosterAddContactSheet.qml
- src/qml/RosterPage.qml
- src/qml/main.qml
It's working already ... although I'm not satisfied with the desgin. Some things can't be fixed because the same bug as on the loginPage appeared. I would like to rework this soon on a kirigami 2 base.
> Add front-end support for roster additions

- src/Kaidan.cpp
- src/MessageHandler.cpp
- src/ServiceDiscoveryManager.cpp
- src/ServiceDiscoveryManager.h
Message carbons allow you to receive the outgoing message of another client of the
same account. In short: messages are synced between the clients.
The handleMessage function of the MessageHandler can now handle both types of messages,
normal, direct messages by a contact and forwarded messages (possibly) written from the same
account.
Notfications and unread message counters are only used, if the message written by somebody
else, so you're not getting annoyed by notifications of your own messages. :)
Closes #116.
> Add XEP-0280: Message Carbons

- src/AvatarFileStorage.cpp
- src/AvatarFileStorage.h
- src/Kaidan.cpp
- src/Kaidan.h
- src/qml/RosterPage.qml
Will be needed to use individual (automatically updating) avatars e.g. on a profile page or for the own avatar.
> Use Q_PROPERTIES instead of SQL fields for avatars

- src/Kaidan.cpp
> getResourcePath: Add binary relative paths

- src/Kaidan.cpp
Before kaidan always search in the source path (also on real installations),
now kaidan only searches in the DEBUG_SOURCE_PATH, if the current build is a
debug build.
> getResourcePath: Only use source path in dbg builds

- misc/qtquickcontrols2.conf
- src/main.cpp
- src/qml/main.qml
Probably especially useful for Plasma Mobile, as it has it's own theme.
This also enables Kaidan to use the system color sheme.
(This change may need discussion)
> Don't force the QtQuickControls Theme

- src/qml/LoginPage.qml
This fixes the word wrapping for the header ("Log in to your XMPP account") and
also contains a code simplification of the serviceBar (the bar where the XMPP
and diaspora icons are in). The layout of the serviceBar in the plasma style is
also fixed, now.
> LoginPage: Fix layout positioning

- src/qml/AboutSheet.qml
- src/qml/LoginPage.qml
- src/qml/RosterRemoveContactSheet.qml
- src/qml/elements/ChatMessage.qml
- src/qml/elements/RosterListItem.qml
This adds explicit textFormat settings in most labels, so labels are always
parsed, if wanted and never if not. So now, the messages aren't parsed anymore,
so the "send image hack" won't work anymore. This is also for security reasons,
because you probably don't want your system to always check any incoming links
in img tags.
> Fix RichText labels in Plasma (Mobile)

- src/qml/elements/ChatMessage.qml
- src/qml/elements/RosterListItem.qml
As promised earlier, I explored font sizing. For me, this change fixes font sizes to make message text easier to read (for comparison, I used Telegram):
Please, verify that it improves font sizes for you, too.
> Fix font sizing

- CMakeLists.txt
The globals for application meta data aren't needed anymore, they're in
branding.h.
> CMakeLists.txt: Clean up and remove old code

- src/ClientWorker.cpp
- src/ClientWorker.h
If the reason for disconnection wasn't user disconnection or authentication
failure, then a 5s timer will be started to reconnect.
> Automatically reconnect 5s after disconnection

- src/ClientThread.cpp
- src/ClientThread.h
- src/ClientWorker.cpp
- src/ClientWorker.h
This fixes that the server wasn't changed after the first connection. The
problem was that gloox::Client::setServer() only sets the server for connecting
to, not the JID that is used to for authenticating on the server. There's a
comment in the documentation that says to change the server manually by getting
a reference of the jid in the client, but that doesn't work since the returned
jid is marked as const.
> Fix not connecting on the first time

- src/Kaidan.cpp
- src/Kaidan.h
- src/qml/main.qml
This will throw a Kirigami passive notification, whenever you try to add or
remove a contact or send a message when being offline. It uses the "long" preset
for the timeout.
> Use passive notifications when online actions fail

- src/ClientWorker.cpp
- src/Kaidan.cpp
When you opened the config file before, you could directly see someone's (or
your own) password, with this it's at least not directly visible to most humans.
Closes #174.
> Encode passwords in base64 to make them not directly visible

- Kaidan.pro
- i18n/base.ts
This adds an empty translation file for creating new translations from the
Weblate WebUI. This won't work fully automated, we will still have to add it to
the QMake and QRC file, so that it'll work correctly with new languages, but the
we could probably grow the number of translators, because not everyone wants to
open an issue on GitHub just to do some translations.
> Add i18n base file for Weblate

- src/qml/RosterPage.qml
First, I only added this for the "Connecting..." state, but I noticed that you
often can't distingush if you're online or not, so from now on it'll also
display if you're offline. I didn't add the online status, because it's the
default case; the functionality is not restricted.
> RosterPage: Display if offline in title

- src/ClientThread.cpp
- src/ClientThread.h
- src/Kaidan.cpp
- src/Kaidan.h
- src/MessageHandler.cpp
- src/MessageHandler.h
- src/MessageModel.cpp
- src/MessageModel.h
This also does some clean up and restructuring of the deployment of the
`chatPartner` property to the ClientThread (MessageHandler) and MessageModel.
Before, a thread-safe function of the ClientThread was used, so the mutex of it
blocked the GUI, when the client thread was busy in this moment.
> Fix lag when changing chat

- src/ServiceDiscoveryManager.cpp
The problem was that the ServiceDiscoveryManager also is a
gloox::ConnectionHandler, but isn't return anything upon a handleTls call, so
this resulted in a true return in gcc (<= 7) in debug mode. gcc (<= 7) in
release mode and gcc-8 and clang in debug mode made it just fail. g++-8
and clang in release mode just gave a segfault.
> Fix release build TLS connection bug!

- src/RosterUpdater.cpp
It will automatically decline *all* subscription requests, now. An UI for
accepting incoming subscription requests will follow.
Thanks to @ge0rg for reporting (#220).
> Roster: Don't automatically accept subscription requests

- Kaidan.pro
- src/CMakeLists.txt
- src/gloox-extensions/gloox-extensions.h
- src/gloox-extensions/hash.cpp
- src/gloox-extensions/hash.h
This implements the hash and hash-used stanza extensions of XEP-0300 in version
0.5. There are no new hash algorithms in this commit, this will probably the job
of the crypto library in gloox.
> Implement XEP-0300: Use of Cryptographic Hash Functions in XMPP

- Kaidan.pro
- src/CMakeLists.txt
- src/gloox-extensions/gloox-extensions.h
- src/gloox-extensions/jinglefile.cpp
- src/gloox-extensions/jinglefile.h
The file stanza extension from Jingle File Upload is now also used for other
protocols as XEP-0385: Stateless Inline Media Sharing (SIMS). Unfortunately,
the original implementation was only usable in a full Jingle File Upload
request. Thus, this new implementation was required. It would be preferable that
this implementation is also used in the normal Jingle session, later.
> Reimplement file stanza extension from XEP-0234: Jingle File Upload

- utils/travis/dependencies.sh
Due to a change at travis-ci, apt update won't be executed at container start
up. Possibilities are to enable it in the travis.yml explicitly again or to do
it manually. Doing it manually is better for us, because we don't need another
apt update at start up for ubuntu touch builds.
> travis: Fix that apt cache is empty at begin

- src/ClientThread.cpp
- src/ClientThread.h
This fixes the error that no custom resource was bound at all and also fixes the
possible resource conflict when starting several instances of kaidan with the
same JID. This is just done by append four random alphanumeric characters to the
resource (many other clients do the same).
Fixes #247.
> Fix resource binding and append four random chars

- src/AvatarFileStorage.cpp
- src/AvatarFileStorage.h
- src/RosterUpdater.cpp
- src/VCardManager.cpp
I made a mistake and somehow forgot to also check if the hash in the vCard based
avatars presence actually differs from the local hash saved for the JID. Thus,
before the vCards were fetched unnecessarily often. To do this I had to use
SHA1 hashes (instead of SHA3-256) for identifying the avatars.
Now the vCards only get fetched on start up, if there's no local avatar saved
for the JID, so if somebody has no avatar in their vCard the vCard will be
fetched every time at start up. Unfortunately this can't be further optimized,
but on the other hand that are just some bytes and I think that's totally ok.
> avatars: Optimize vCard fetchment, Use SHA1 hashes locally

- utils/build-click.sh
It's integrated to Ubuntu Touch now ;)
> ubuntu-touch: Remove dependency of QQC2
