KaidanIM/Kaidan

app/kaidan.pro
I think minor bug fixes like this can also be merged without approvals from two other core devs. But I think we should post the link in the jabber channel and wait ~5 min for answers.
=> kaidan.pro: Fix file name (sourc -> source)

app/kaidan.pro, app/resources/deployment.pri, app/resources/main.qml, app/resources/qml.qrc, app/source/EchoPayload.h, app/source/EchoPayloadParserFactory.h, app/source/EchoPayloadSerializer.h, app/source/Kaidan.cpp, app/source/Kaidan.h, app/source/RosterContoller.cpp, app/source/RosterContoller.h, app/source/RosterItem.cpp, app/source/RosterItem.h, app/source/main.cpp
Now Kaidan disconnects on exit.
Also added Flickable to make roster scrollable (drag to scroll).
=> Minor UI changes and graceful exit

app/resources/LoginPage.qml, app/resources/RosterPage.qml, app/resources/main.qml, app/resources/qml.qrc, app/source/Kaidan.cpp, app/source/Kaidan.h
This adds simple login screen where you can enter your JID and password.
=> Add simple login screen

src/Kaidan.cpp, src/qml/LoginPage.qml, src/qml/RosterPage.qml, src/qml/main.qml
According to https://github.com/KaidanIM/Kaidan/issues/23 coding style is fixed.
=> Clean up coding style

src/qml/LoginPage.qml, src/qml/RosterPage.qml, src/qml/main.qml
Just a WIP PR, so everyone can see what I am doing.
=> Add Kirigami UI

README.md
This won't actually change anything. I just prefer this way.
=> README: Use lowercase letters for URLs

README.md
Version number and downloads are currently not working, because we don't have any release.
Preview:
https://github.com/LNJ2/Kaidan/blob/readmelabels/README.md
Other labels:
http://shields.io/
=> README: Add some awesome shields.io labels

CMakeLists.txt, src/Kaidan.cpp, src/main.cpp
New global variables in C++ are:
```
APPLICATION_NAME
APPLICATION_DISPLAY_NAME
APPLICATION_ID
VERSION_STRING
```
=> Pass version and name variables from cmake to C++

src/qml/ChatPage.qml
I think the title says all, and it's not such a huge change :D
=> ChatPage: Make text selectable

.gitmodules
We could also add other 3rd party libraries in libs/.
A tutorial for submodules can be found here: https://git-scm.com/book/en/v2/Git-Tools-Submodules
=> Add KaidanIM/KaidanSF as submodule in libs/kaidansf/

LICENSE.txt
=> LICENSE: Add missing copyright of banner.png

README.md
A screenshot with the Kaidan logo might be also good.
=> README: Add an about text

data/images/kaidan.svg, i18n/de.ts, i18n/fr.ts, i18n/ja.ts, i18n/ru.ts, kaidan_qml.qrc, src/Kaidan.cpp, src/Kaidan.h, src/qml/AboutPage.qml, src/qml/main.qml
This adds an about page showing the version number, an icon, the copyright and the licenses
=> Add about page

src/Kaidan.cpp, src/RosterController.cpp, src/RosterController.h, src/RosterModel.cpp, src/RosterModel.h
Now the roster is updated when a Contact was added/removed, the name of a JID was updated or the roster was completely reset.
=> Add automatic roster refreshing

src/qml/AboutPage.qml, src/qml/ChatPage.qml, src/qml/LoginPage.qml, src/qml/RosterPage.qml, src/qml/main.qml
Please do not only check the code, but test build and use it, so I can see what has been changed in kirigami 2
Closes #80
=> [WIP] Port to Kirigami 2

kaidan_qml.qrc, src/qml/RosterPage.qml, src/qml/RosterRemoveContactSheet.qml
=> Roster: Add confirmation dialog for contact del.

src/Kaidan.cpp, src/MessageController.cpp, src/MessageModel.cpp, src/MessageModel.h, src/Notifications.h, src/PresenceController.cpp, src/RosterController.cpp, src/RosterModel.cpp, src/ServiceDiscoveryManager.cpp, src/ServiceDiscoveryManager.h, src/VCard.cpp, src/VCardController.cpp, src/main.cpp
=> Switch to KDE's C++ coding style

CMakeLists.txt
This will show the user which libraries are found, which version of them
is being used and which libraries have not been found.
=> CMake: Add feature summary

src/CMakeLists.txt, src/Database.cpp, src/Database.h, src/Kaidan.cpp, src/Kaidan.h, src/MessageController.cpp, src/MessageController.h, src/MessageModel.cpp, src/MessageModel.h, src/RosterController.cpp, src/RosterController.h, src/RosterModel.cpp, src/RosterModel.h, src/main.cpp
=> Add database versioning and conversion

src/AvatarFileStorage.cpp, src/AvatarFileStorage.h, src/CMakeLists.txt, src/Database.cpp, src/Kaidan.cpp, src/Kaidan.h, src/RosterManager.cpp, src/RosterModel.cpp, src/RosterModel.h, src/RosterUpdater.cpp, src/RosterUpdater.h, src/VCardManager.cpp, src/VCardManager.h, src/qml/RosterPage.qml, src/qml/elements/RosterListItem.qml
=> Add VCard-based avatars via. XEP-0054: vcard-temp

i18n/0_i18n.qrc, i18n/ms.ts
I can't translate via Weblate, it just says "failed to create new language"... so I'm adding translations through GitHub.
=> Add Malay translation

src/Database.cpp
There was just one comma too much, that broke everything. Idk why I
haven't noticed that before ...
Fixes #132.
=> Database: Fix error in database creation

src/qml/ChatPage.qml
=> ChatPage: Fix recipient's avatar displayed

misc/kaidan.desktop
https://standards.freedesktop.org/menu-spec/latest/apa.html
Reference:
https://github.com/AppImage/appimage.github.io/pull/191
=> Categories=Network;

utils/AppImage.sh
Originally by @probonopd
https://github.com/KaidanIM/Kaidan/issues/141#issuecomment-346896890
=> AppImage.sh: Use release build, Correct install path

.travis.yml, utils/travis-build.sh, utils/travis-dependencies.sh
This seems to work already, but most likely the code is not really clean yet. I'll clean it up tomorrow if needed
=> Travis-ci: Build on Ubuntu Trusty

src/qml/GlobalDrawer.qml, src/qml/RosterPage.qml, src/qml/main.qml
=> RosterPage: Make 'Add contact' the main action

i18n/ru.ts
=> Russian translation fixes

README.md
preview: https://github.com/LNJ2/Kaidan/blob/feature/readme-new-screenshots/README.md
=> README: New screenshot, Update description

src/ClientThread.cpp, src/ClientThread.h, src/ClientWorker.cpp, src/ClientWorker.h, src/Kaidan.cpp, src/Kaidan.h, src/main.cpp
This will give the XMPP server the information if the user is currently actively
using Kaidan or it's runnning in the background. If it's running in the
background, the server will only send some important messages, not everything.
=> Add XEP-0352: Client State Indication

README.md
Please merge once the Plasma Mobile Ci is fixed :)
=> README.md: Add Plasma Mobile CI build label

src/qml/LoginPage.qml
=> Add different connection error messages

CMakeLists.txt, src/main.cpp
on desktop systems, use qapplication, which makes possible to use qwidget-based qqc2 styles.
on a Plasma Desktop session, the breeze style will be used
=> use QApplication when qwidgets found

src/qml/elements/RosterListItem.qml
=> RosterPage: Fix names are displayed too short

src/RosterUpdater.cpp
=> Fix VCards of newly added contacts are not loaded

src/ClientThread.h, src/Kaidan.cpp, src/Kaidan.h, src/RosterManager.cpp, src/RosterManager.h, src/qml/elements/RosterAddContactSheet.qml
=> AddContactSheet: Add optional message for subscription request

Kaidan.pro, src/CMakeLists.txt, src/gloox-extensions/bitsofbinarycache.h, src/gloox-extensions/bitsofbinarydata.cpp, src/gloox-extensions/bitsofbinarydata.h, src/gloox-extensions/bitsofbinaryhandler.h, src/gloox-extensions/bitsofbinarymanager.cpp, src/gloox-extensions/bitsofbinarymanager.h, src/gloox-extensions/bitsofbinarymemorycache.cpp, src/gloox-extensions/bitsofbinarymemorycache.h, src/gloox-extensions/gloox-extensions.h
=> Implement XEP-0231: Bits of Binary

Kaidan.pro, src/CMakeLists.txt, src/gloox-extensions/gloox-extensions.h, src/gloox-extensions/reference.cpp, src/gloox-extensions/reference.h
This implements the StanzaExtension of the reference element of XEP-0372.
=> Implement XEP-0372: References

README.md, kaidan_qml.qrc, kirigami-icons.qrc, src/qml/ChatPage.qml, src/qml/elements/IconButton.qml
If Kaidan runs on a mobile system, the drawer from the picture will be shown. On the desktop, a file dialog is directly opened.
=> Initial file upload gui

src/gloox-extensions/gloox-extensions.h, src/gloox-extensions/sims.cpp, src/gloox-extensions/sims.h
This implements XEP-0385 as in version 0.2 as StanzaExtension.
Closes #127.
With this XEP implementation for file uploads has been finished. :smiley:
=> Implement XEP-0385: Stateless Inline Media Sharing (SIMS)

i18n/base.ts, i18n/de.ts, i18n/es.ts, i18n/fr.ts, i18n/ja.ts, i18n/ms.ts, i18n/nb.ts, i18n/nl.ts, i18n/pt.ts, i18n/ru.ts, kaidan_qml.qrc, src/qml/EmptyChatPage.qml, src/qml/main.qml
=> Display a help text if no contact is selected

misc/ubuntu-touch/apparmor.json
According to https://forums.ubports.com/topic/1215/updating-apps-to-16-04
=> ubuntu-touch: update apparmor policy version

src/ClientThread.cpp, src/MessageHandler.cpp, src/MessageHandler.h
There won't be any notifications for messages that were just synced from other
clients anymore.
=> MessageHandler: No notifications for carbon messages

src/MessageHandler.cpp, src/MessageModel.cpp
Finally got fixed! :)
Fixes #159.
=> MessageHandler: Fix timezone bug of timestamps, Clean up

src/qml/LoginPage.qml
More responsive design for login page.
Rearranging the gui elements among each other.
---
=> Redesign login page
